spring.application.name=order-service
server.port=8082

# URL do product-service
product.service.url=${PRODUCT_SERVICE_URL:http://localhost:8081}

product.service.timeout-ms=${PRODUCT_SERVICE_TIMEOUT_MS:3000}
